/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.jooq.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import net.snet.crm.infra.db.jooq.tables.NetworkNodesView;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "network_nodes_view", schema = "public")
public class NetworkNodesViewRecord extends TableRecordImpl<NetworkNodesViewRecord> implements Record9<Integer, String, String, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1121856982;

    /**
     * Setter for <code>public.network_nodes_view.id</code>.
     */
    public NetworkNodesViewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.id</code>.
     */
    @Column(name = "id", precision = 32)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.network_nodes_view.name</code>.
     */
    public NetworkNodesViewRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.name</code>.
     */
    @Column(name = "name", length = 50)
    @Size(max = 50)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.network_nodes_view.master</code>.
     */
    public NetworkNodesViewRecord setMaster(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.master</code>.
     */
    @Column(name = "master", length = 50)
    @Size(max = 50)
    public String getMaster() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.network_nodes_view.area</code>.
     */
    public NetworkNodesViewRecord setArea(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.area</code>.
     */
    @Column(name = "area", length = 50)
    @Size(max = 50)
    public String getArea() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.network_nodes_view.vendor</code>.
     */
    public NetworkNodesViewRecord setVendor(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.vendor</code>.
     */
    @Column(name = "vendor", length = 50)
    @Size(max = 50)
    public String getVendor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.network_nodes_view.model</code>.
     */
    public NetworkNodesViewRecord setModel(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.model</code>.
     */
    @Column(name = "model", length = 50)
    @Size(max = 50)
    public String getModel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.network_nodes_view.linkTo</code>.
     */
    public NetworkNodesViewRecord setLinkto(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.linkTo</code>.
     */
    @Column(name = "linkTo", length = 50)
    @Size(max = 50)
    public String getLinkto() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.network_nodes_view.rstpNumRing</code>.
     */
    public NetworkNodesViewRecord setRstpnumring(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.rstpNumRing</code>.
     */
    @Column(name = "rstpNumRing", precision = 32)
    public Integer getRstpnumring() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.network_nodes_view.backupPath</code>.
     */
    public NetworkNodesViewRecord setBackuppath(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.network_nodes_view.backupPath</code>.
     */
    @Column(name = "backupPath")
    public String getBackuppath() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, String, String, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NetworkNodesView.NETWORK_NODES_VIEW.ID;
    }

    @Override
    public Field<String> field2() {
        return NetworkNodesView.NETWORK_NODES_VIEW.NAME;
    }

    @Override
    public Field<String> field3() {
        return NetworkNodesView.NETWORK_NODES_VIEW.MASTER;
    }

    @Override
    public Field<String> field4() {
        return NetworkNodesView.NETWORK_NODES_VIEW.AREA;
    }

    @Override
    public Field<String> field5() {
        return NetworkNodesView.NETWORK_NODES_VIEW.VENDOR;
    }

    @Override
    public Field<String> field6() {
        return NetworkNodesView.NETWORK_NODES_VIEW.MODEL;
    }

    @Override
    public Field<String> field7() {
        return NetworkNodesView.NETWORK_NODES_VIEW.LINKTO;
    }

    @Override
    public Field<Integer> field8() {
        return NetworkNodesView.NETWORK_NODES_VIEW.RSTPNUMRING;
    }

    @Override
    public Field<String> field9() {
        return NetworkNodesView.NETWORK_NODES_VIEW.BACKUPPATH;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getMaster();
    }

    @Override
    public String component4() {
        return getArea();
    }

    @Override
    public String component5() {
        return getVendor();
    }

    @Override
    public String component6() {
        return getModel();
    }

    @Override
    public String component7() {
        return getLinkto();
    }

    @Override
    public Integer component8() {
        return getRstpnumring();
    }

    @Override
    public String component9() {
        return getBackuppath();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getMaster();
    }

    @Override
    public String value4() {
        return getArea();
    }

    @Override
    public String value5() {
        return getVendor();
    }

    @Override
    public String value6() {
        return getModel();
    }

    @Override
    public String value7() {
        return getLinkto();
    }

    @Override
    public Integer value8() {
        return getRstpnumring();
    }

    @Override
    public String value9() {
        return getBackuppath();
    }

    @Override
    public NetworkNodesViewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value3(String value) {
        setMaster(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value4(String value) {
        setArea(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value5(String value) {
        setVendor(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value6(String value) {
        setModel(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value7(String value) {
        setLinkto(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value8(Integer value) {
        setRstpnumring(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord value9(String value) {
        setBackuppath(value);
        return this;
    }

    @Override
    public NetworkNodesViewRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkNodesViewRecord
     */
    public NetworkNodesViewRecord() {
        super(NetworkNodesView.NETWORK_NODES_VIEW);
    }

    /**
     * Create a detached, initialised NetworkNodesViewRecord
     */
    public NetworkNodesViewRecord(Integer id, String name, String master, String area, String vendor, String model, String linkto, Integer rstpnumring, String backuppath) {
        super(NetworkNodesView.NETWORK_NODES_VIEW);

        set(0, id);
        set(1, name);
        set(2, master);
        set(3, area);
        set(4, vendor);
        set(5, model);
        set(6, linkto);
        set(7, rstpnumring);
        set(8, backuppath);
    }
}
