/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.command;


import javax.annotation.Generated;

import net.snet.crm.infra.db.command.tables.Customers;
import net.snet.crm.infra.db.command.tables.Services;
import net.snet.crm.infra.db.command.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_HISTORY_ID_KEY = Indexes0.CUSTOMERS_HISTORY_ID_KEY;
    public static final Index CUSTOMERS_PKEY = Indexes0.CUSTOMERS_PKEY;
    public static final Index CUSTOMERS_SEARCH_IDX = Indexes0.CUSTOMERS_SEARCH_IDX;
    public static final Index CUSTOMER_INDEX2 = Indexes0.CUSTOMER_INDEX2;
    public static final Index SERVICES_PKEY = Indexes0.SERVICES_PKEY;
    public static final Index SERVICES_SEARCH_IDX = Indexes0.SERVICES_SEARCH_IDX;
    public static final Index SIS_USER_LOGIN_KEY = Indexes0.SIS_USER_LOGIN_KEY;
    public static final Index SIS_USER_NAME_KEY = Indexes0.SIS_USER_NAME_KEY;
    public static final Index SIS_USER_PKEY = Indexes0.SIS_USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_HISTORY_ID_KEY = Internal.createIndex("customers_history_id_key", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.HISTORY_ID }, true);
        public static Index CUSTOMERS_PKEY = Internal.createIndex("customers_pkey", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.ID }, true);
        public static Index CUSTOMERS_SEARCH_IDX = Internal.createIndex("customers_search_idx", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.LEXEMS }, false);
        public static Index CUSTOMER_INDEX2 = Internal.createIndex("customer_index2", Services.SERVICES, new OrderField[] { Services.SERVICES.CUSTOMER_ID }, false);
        public static Index SERVICES_PKEY = Internal.createIndex("services_pkey", Services.SERVICES, new OrderField[] { Services.SERVICES.ID }, true);
        public static Index SERVICES_SEARCH_IDX = Internal.createIndex("services_search_idx", Services.SERVICES, new OrderField[] { Services.SERVICES.LEXEMS }, false);
        public static Index SIS_USER_LOGIN_KEY = Internal.createIndex("sis_user_login_key", Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
        public static Index SIS_USER_NAME_KEY = Internal.createIndex("sis_user_name_key", Users.USERS, new OrderField[] { Users.USERS.NAME }, true);
        public static Index SIS_USER_PKEY = Internal.createIndex("sis_user_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
