/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.command;


import javax.annotation.Generated;

import net.snet.crm.infra.db.command.tables.Customers;
import net.snet.crm.infra.db.command.tables.Services;
import net.snet.crm.infra.db.command.tables.Users;
import net.snet.crm.infra.db.command.tables.records.CustomersRecord;
import net.snet.crm.infra.db.command.tables.records.ServicesRecord;
import net.snet.crm.infra.db.command.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = UniqueKeys0.CUSTOMERS_PKEY;
    public static final UniqueKey<CustomersRecord> CUSTOMERS_HISTORY_ID_KEY = UniqueKeys0.CUSTOMERS_HISTORY_ID_KEY;
    public static final UniqueKey<ServicesRecord> SERVICES_PKEY = UniqueKeys0.SERVICES_PKEY;
    public static final UniqueKey<UsersRecord> SIS_USER_PKEY = UniqueKeys0.SIS_USER_PKEY;
    public static final UniqueKey<UsersRecord> SIS_USER_LOGIN_KEY = UniqueKeys0.SIS_USER_LOGIN_KEY;
    public static final UniqueKey<UsersRecord> SIS_USER_NAME_KEY = UniqueKeys0.SIS_USER_NAME_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ServicesRecord, CustomersRecord> SERVICES__FK5235105E31F2D3D = ForeignKeys0.SERVICES__FK5235105E31F2D3D;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = Internal.createUniqueKey(Customers.CUSTOMERS, "customers_pkey", Customers.CUSTOMERS.ID);
        public static final UniqueKey<CustomersRecord> CUSTOMERS_HISTORY_ID_KEY = Internal.createUniqueKey(Customers.CUSTOMERS, "customers_history_id_key", Customers.CUSTOMERS.HISTORY_ID);
        public static final UniqueKey<ServicesRecord> SERVICES_PKEY = Internal.createUniqueKey(Services.SERVICES, "services_pkey", Services.SERVICES.ID);
        public static final UniqueKey<UsersRecord> SIS_USER_PKEY = Internal.createUniqueKey(Users.USERS, "sis_user_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> SIS_USER_LOGIN_KEY = Internal.createUniqueKey(Users.USERS, "sis_user_login_key", Users.USERS.LOGIN);
        public static final UniqueKey<UsersRecord> SIS_USER_NAME_KEY = Internal.createUniqueKey(Users.USERS, "sis_user_name_key", Users.USERS.NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ServicesRecord, CustomersRecord> SERVICES__FK5235105E31F2D3D = Internal.createForeignKey(net.snet.crm.infra.db.command.Keys.CUSTOMERS_PKEY, Services.SERVICES, "services__fk5235105e31f2d3d", Services.SERVICES.CUSTOMER_ID);
    }
}
