/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.command;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.snet.crm.infra.db.command.tables.Customers;
import net.snet.crm.infra.db.command.tables.Network;
import net.snet.crm.infra.db.command.tables.Services;
import net.snet.crm.infra.db.command.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1424044224;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.customers</code>.
     */
    public final Customers CUSTOMERS = net.snet.crm.infra.db.command.tables.Customers.CUSTOMERS;

    /**
     * The table <code>public.network</code>.
     */
    public final Network NETWORK = net.snet.crm.infra.db.command.tables.Network.NETWORK;

    /**
     * The table <code>public.services</code>.
     */
    public final Services SERVICES = net.snet.crm.infra.db.command.tables.Services.SERVICES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = net.snet.crm.infra.db.command.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customers.CUSTOMERS,
            Network.NETWORK,
            Services.SERVICES,
            Users.USERS);
    }
}
