/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.command;


import javax.annotation.Generated;

import net.snet.crm.infra.db.command.tables.Customers;
import net.snet.crm.infra.db.command.tables.NetworkNodesView;
import net.snet.crm.infra.db.command.tables.Services;
import net.snet.crm.infra.db.command.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.network_nodes_view</code>.
     */
    public static final NetworkNodesView NETWORK_NODES_VIEW = NetworkNodesView.NETWORK_NODES_VIEW;

    /**
     * The table <code>public.services</code>.
     */
    public static final Services SERVICES = Services.SERVICES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
