/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "network_nodes_view", schema = "public")
public class NetworkNodesView implements Serializable {

    private static final long serialVersionUID = -43159989;

    private final Integer id;
    private final String  name;
    private final String  master;
    private final String  area;
    private final String  vendor;
    private final String  model;
    private final String  linkto;
    private final Integer rstpnumring;
    private final String  backuppath;

    public NetworkNodesView(NetworkNodesView value) {
        this.id = value.id;
        this.name = value.name;
        this.master = value.master;
        this.area = value.area;
        this.vendor = value.vendor;
        this.model = value.model;
        this.linkto = value.linkto;
        this.rstpnumring = value.rstpnumring;
        this.backuppath = value.backuppath;
    }

    public NetworkNodesView(
        Integer id,
        String  name,
        String  master,
        String  area,
        String  vendor,
        String  model,
        String  linkto,
        Integer rstpnumring,
        String  backuppath
    ) {
        this.id = id;
        this.name = name;
        this.master = master;
        this.area = area;
        this.vendor = vendor;
        this.model = model;
        this.linkto = linkto;
        this.rstpnumring = rstpnumring;
        this.backuppath = backuppath;
    }

    @Column(name = "id", precision = 32)
    public Integer getId() {
        return this.id;
    }

    @Column(name = "name", length = 50)
    @Size(max = 50)
    public String getName() {
        return this.name;
    }

    @Column(name = "master", length = 50)
    @Size(max = 50)
    public String getMaster() {
        return this.master;
    }

    @Column(name = "area", length = 50)
    @Size(max = 50)
    public String getArea() {
        return this.area;
    }

    @Column(name = "vendor", length = 50)
    @Size(max = 50)
    public String getVendor() {
        return this.vendor;
    }

    @Column(name = "model", length = 50)
    @Size(max = 50)
    public String getModel() {
        return this.model;
    }

    @Column(name = "linkTo", length = 50)
    @Size(max = 50)
    public String getLinkto() {
        return this.linkto;
    }

    @Column(name = "rstpNumRing", precision = 32)
    public Integer getRstpnumring() {
        return this.rstpnumring;
    }

    @Column(name = "backupPath")
    public String getBackuppath() {
        return this.backuppath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NetworkNodesView (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(master);
        sb.append(", ").append(area);
        sb.append(", ").append(vendor);
        sb.append(", ").append(model);
        sb.append(", ").append(linkto);
        sb.append(", ").append(rstpnumring);
        sb.append(", ").append(backuppath);

        sb.append(")");
        return sb.toString();
    }
}
