/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.query;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.snet.crm.infra.db.query.tables.Nodes;
import net.snet.crm.infra.db.query.tables.NodesDetail;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Query extends SchemaImpl {

    private static final long serialVersionUID = 9074104;

    /**
     * The reference instance of <code>query</code>
     */
    public static final Query QUERY = new Query();

    /**
     * The table <code>query.nodes</code>.
     */
    public final Nodes NODES = net.snet.crm.infra.db.query.tables.Nodes.NODES;

    /**
     * The table <code>query.nodes_detail</code>.
     */
    public final NodesDetail NODES_DETAIL = net.snet.crm.infra.db.query.tables.NodesDetail.NODES_DETAIL;

    /**
     * No further instances allowed
     */
    private Query() {
        super("query", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Nodes.NODES,
            NodesDetail.NODES_DETAIL);
    }
}
