/*
 * This file is generated by jOOQ.
 */
package net.snet.crm.infra.db.command.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import net.snet.crm.infra.db.command.tables.Network;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "network", schema = "public", uniqueConstraints = {
    @UniqueConstraint(name = "network_pkey", columnNames = {"id"}),
    @UniqueConstraint(name = "network_name_key", columnNames = {"name"})
}, indexes = {
    @Index(name = "network_name_key", unique = true, columnList = "name ASC"),
    @Index(name = "network_pkey", unique = true, columnList = "id ASC")
})
public class NetworkRecord extends UpdatableRecordImpl<NetworkRecord> {

    private static final long serialVersionUID = -778746247;

    /**
     * Setter for <code>public.network.id</code>.
     */
    public NetworkRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.network.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 32)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.network.name</code>.
     */
    public NetworkRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.network.name</code>.
     */
    @Column(name = "name", nullable = false, length = 50)
    @NotNull
    @Size(max = 50)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.network.info</code>.
     */
    public NetworkRecord setInfo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.network.info</code>.
     */
    @Column(name = "info", length = 500)
    @Size(max = 500)
    public String getInfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.network.active</code>.
     */
    public NetworkRecord setActive(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.network.active</code>.
     */
    @Column(name = "active")
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.network.type</code>.
     */
    public NetworkRecord setType(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.network.type</code>.
     */
    @Column(name = "type", precision = 32)
    public Integer getType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.network.mode</code>.
     */
    public NetworkRecord setMode(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.network.mode</code>.
     */
    @Column(name = "mode", precision = 32)
    public Integer getMode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.network.wds</code>.
     */
    public NetworkRecord setWds(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.network.wds</code>.
     */
    @Column(name = "wds")
    public Boolean getWds() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.network.frequency</code>.
     */
    public NetworkRecord setFrequency(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.network.frequency</code>.
     */
    @Column(name = "frequency", precision = 32)
    public Integer getFrequency() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.network.vendor</code>.
     */
    public NetworkRecord setVendor(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.network.vendor</code>.
     */
    @Column(name = "vendor", length = 50)
    @Size(max = 50)
    public String getVendor() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.network.azimuth</code>.
     */
    public NetworkRecord setAzimuth(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.network.azimuth</code>.
     */
    @Column(name = "azimuth", length = 50)
    @Size(max = 50)
    public String getAzimuth() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.network.ssid</code>.
     */
    public NetworkRecord setSsid(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.network.ssid</code>.
     */
    @Column(name = "ssid", length = 50)
    @Size(max = 50)
    public String getSsid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.network.auth</code>.
     */
    public NetworkRecord setAuth(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.network.auth</code>.
     */
    @Column(name = "auth", length = 50)
    @Size(max = 50)
    public String getAuth() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.network.polarization</code>.
     */
    public NetworkRecord setPolarization(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.network.polarization</code>.
     */
    @Column(name = "polarization", precision = 32)
    public Integer getPolarization() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.network.country</code>.
     */
    public NetworkRecord setCountry(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.network.country</code>.
     */
    @Column(name = "country", precision = 32)
    public Integer getCountry() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.network.norm</code>.
     */
    public NetworkRecord setNorm(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.network.norm</code>.
     */
    @Column(name = "norm", length = 50)
    @Size(max = 50)
    public String getNorm() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.network.area</code>.
     */
    public NetworkRecord setArea(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.network.area</code>.
     */
    @Column(name = "area", length = 50)
    @Size(max = 50)
    public String getArea() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.network.aggregation</code>.
     */
    public NetworkRecord setAggregation(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.network.aggregation</code>.
     */
    @Column(name = "aggregation")
    public Boolean getAggregation() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.network.width</code>.
     */
    public NetworkRecord setWidth(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.network.width</code>.
     */
    @Column(name = "width", length = 50)
    @Size(max = 50)
    public String getWidth() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.network.antenna</code>.
     */
    public NetworkRecord setAntenna(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.network.antenna</code>.
     */
    @Column(name = "antenna", length = 50)
    @Size(max = 50)
    public String getAntenna() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.network.power</code>.
     */
    public NetworkRecord setPower(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.network.power</code>.
     */
    @Column(name = "power", length = 50)
    @Size(max = 50)
    public String getPower() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.network.master</code>.
     */
    public NetworkRecord setMaster(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.network.master</code>.
     */
    @Column(name = "master", length = 50)
    @Size(max = 50)
    public String getMaster() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.network.linkto</code>.
     */
    public NetworkRecord setLinkto(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.network.linkto</code>.
     */
    @Column(name = "linkto", length = 50)
    @Size(max = 50)
    public String getLinkto() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.network.hardware</code>.
     */
    public NetworkRecord setHardware(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.network.hardware</code>.
     */
    @Column(name = "hardware", length = 50)
    @Size(max = 50)
    public String getHardware() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.network.tdma</code>.
     */
    public NetworkRecord setTdma(Boolean value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>public.network.tdma</code>.
     */
    @Column(name = "tdma")
    public Boolean getTdma() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>public.network.latitude</code>.
     */
    public NetworkRecord setLatitude(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>public.network.latitude</code>.
     */
    @Column(name = "latitude", length = 50)
    @Size(max = 50)
    public String getLatitude() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.network.longitude</code>.
     */
    public NetworkRecord setLongitude(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>public.network.longitude</code>.
     */
    @Column(name = "longitude", length = 50)
    @Size(max = 50)
    public String getLongitude() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.network.r_updatetime</code>.
     */
    public NetworkRecord setRUpdatetime(Timestamp value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_updatetime</code>.
     */
    @Column(name = "r_updatetime")
    public Timestamp getRUpdatetime() {
        return (Timestamp) get(26);
    }

    /**
     * Setter for <code>public.network.r_firmware</code>.
     */
    public NetworkRecord setRFirmware(String value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_firmware</code>.
     */
    @Column(name = "r_firmware", length = 50)
    @Size(max = 50)
    public String getRFirmware() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.network.r_platform</code>.
     */
    public NetworkRecord setRPlatform(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_platform</code>.
     */
    @Column(name = "r_platform", length = 50)
    @Size(max = 50)
    public String getRPlatform() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.network.r_signal</code>.
     */
    public NetworkRecord setRSignal(String value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_signal</code>.
     */
    @Column(name = "r_signal", length = 50)
    @Size(max = 50)
    public String getRSignal() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.network.r_ccq</code>.
     */
    public NetworkRecord setRCcq(String value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_ccq</code>.
     */
    @Column(name = "r_ccq", length = 50)
    @Size(max = 50)
    public String getRCcq() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.network.r_txrate</code>.
     */
    public NetworkRecord setRTxrate(String value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_txrate</code>.
     */
    @Column(name = "r_txrate", length = 50)
    @Size(max = 50)
    public String getRTxrate() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.network.r_rxrate</code>.
     */
    public NetworkRecord setRRxrate(String value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_rxrate</code>.
     */
    @Column(name = "r_rxrate", length = 50)
    @Size(max = 50)
    public String getRRxrate() {
        return (String) get(32);
    }

    /**
     * Setter for <code>public.network.r_quality</code>.
     */
    public NetworkRecord setRQuality(String value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_quality</code>.
     */
    @Column(name = "r_quality", length = 50)
    @Size(max = 50)
    public String getRQuality() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.network.r_capacity</code>.
     */
    public NetworkRecord setRCapacity(String value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_capacity</code>.
     */
    @Column(name = "r_capacity", length = 50)
    @Size(max = 50)
    public String getRCapacity() {
        return (String) get(34);
    }

    /**
     * Setter for <code>public.network.r_lanspeed</code>.
     */
    public NetworkRecord setRLanspeed(String value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_lanspeed</code>.
     */
    @Column(name = "r_lanspeed", length = 50)
    @Size(max = 50)
    public String getRLanspeed() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.network.r_txpower</code>.
     */
    public NetworkRecord setRTxpower(String value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_txpower</code>.
     */
    @Column(name = "r_txpower", length = 50)
    @Size(max = 50)
    public String getRTxpower() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.network.monitoring</code>.
     */
    public NetworkRecord setMonitoring(String value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>public.network.monitoring</code>.
     */
    @Column(name = "monitoring", length = 50)
    @Size(max = 50)
    public String getMonitoring() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.network.traceroute</code>.
     */
    public NetworkRecord setTraceroute(String value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>public.network.traceroute</code>.
     */
    @Column(name = "traceroute")
    public String getTraceroute() {
        return (String) get(38);
    }

    /**
     * Setter for <code>public.network.ping</code>.
     */
    public NetworkRecord setPing(String value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for <code>public.network.ping</code>.
     */
    @Column(name = "ping", length = 50)
    @Size(max = 50)
    public String getPing() {
        return (String) get(39);
    }

    /**
     * Setter for <code>public.network.r_frequency</code>.
     */
    public NetworkRecord setRFrequency(Integer value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for <code>public.network.r_frequency</code>.
     */
    @Column(name = "r_frequency", precision = 32)
    public Integer getRFrequency() {
        return (Integer) get(40);
    }

    /**
     * Setter for <code>public.network.model</code>.
     */
    public NetworkRecord setModel(String value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for <code>public.network.model</code>.
     */
    @Column(name = "model", length = 50)
    @Size(max = 50)
    public String getModel() {
        return (String) get(41);
    }

    /**
     * Setter for <code>public.network.uplink_port</code>.
     */
    public NetworkRecord setUplinkPort(String value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for <code>public.network.uplink_port</code>.
     */
    @Column(name = "uplink_port", length = 50)
    @Size(max = 50)
    public String getUplinkPort() {
        return (String) get(42);
    }

    /**
     * Setter for <code>public.network.rstp_num_ring</code>.
     */
    public NetworkRecord setRstpNumRing(Integer value) {
        set(43, value);
        return this;
    }

    /**
     * Getter for <code>public.network.rstp_num_ring</code>.
     */
    @Column(name = "rstp_num_ring", precision = 32)
    public Integer getRstpNumRing() {
        return (Integer) get(43);
    }

    /**
     * Setter for <code>public.network.uplink_sfp_tx</code>.
     */
    public NetworkRecord setUplinkSfpTx(Integer value) {
        set(44, value);
        return this;
    }

    /**
     * Getter for <code>public.network.uplink_sfp_tx</code>.
     */
    @Column(name = "uplink_sfp_tx", precision = 32)
    public Integer getUplinkSfpTx() {
        return (Integer) get(44);
    }

    /**
     * Setter for <code>public.network.linkto_port</code>.
     */
    public NetworkRecord setLinktoPort(String value) {
        set(45, value);
        return this;
    }

    /**
     * Getter for <code>public.network.linkto_port</code>.
     */
    @Column(name = "linkto_port", length = 50)
    @Size(max = 50)
    public String getLinktoPort() {
        return (String) get(45);
    }

    /**
     * Setter for <code>public.network.service</code>.
     */
    public NetworkRecord setService(Integer value) {
        set(46, value);
        return this;
    }

    /**
     * Getter for <code>public.network.service</code>.
     */
    @Column(name = "service", precision = 32)
    public Integer getService() {
        return (Integer) get(46);
    }

    /**
     * Setter for <code>public.network.port_info</code>.
     */
    public NetworkRecord setPortInfo(String value) {
        set(47, value);
        return this;
    }

    /**
     * Getter for <code>public.network.port_info</code>.
     */
    @Column(name = "port_info", length = 500)
    @Size(max = 500)
    public String getPortInfo() {
        return (String) get(47);
    }

    /**
     * Setter for <code>public.network.zbx_groups</code>.
     */
    public NetworkRecord setZbxGroups(String value) {
        set(48, value);
        return this;
    }

    /**
     * Getter for <code>public.network.zbx_groups</code>.
     */
    @Column(name = "zbx_groups", length = 100)
    @Size(max = 100)
    public String getZbxGroups() {
        return (String) get(48);
    }

    /**
     * Setter for <code>public.network.version</code>.
     */
    public NetworkRecord setVersion(Integer value) {
        set(49, value);
        return this;
    }

    /**
     * Getter for <code>public.network.version</code>.
     */
    @Column(name = "version", nullable = false, precision = 32)
    public Integer getVersion() {
        return (Integer) get(49);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkRecord
     */
    public NetworkRecord() {
        super(Network.NETWORK);
    }

    /**
     * Create a detached, initialised NetworkRecord
     */
    public NetworkRecord(Integer id, String name, String info, Boolean active, Integer type, Integer mode, Boolean wds, Integer frequency, String vendor, String azimuth, String ssid, String auth, Integer polarization, Integer country, String norm, String area, Boolean aggregation, String width, String antenna, String power, String master, String linkto, String hardware, Boolean tdma, String latitude, String longitude, Timestamp rUpdatetime, String rFirmware, String rPlatform, String rSignal, String rCcq, String rTxrate, String rRxrate, String rQuality, String rCapacity, String rLanspeed, String rTxpower, String monitoring, String traceroute, String ping, Integer rFrequency, String model, String uplinkPort, Integer rstpNumRing, Integer uplinkSfpTx, String linktoPort, Integer service, String portInfo, String zbxGroups, Integer version) {
        super(Network.NETWORK);

        set(0, id);
        set(1, name);
        set(2, info);
        set(3, active);
        set(4, type);
        set(5, mode);
        set(6, wds);
        set(7, frequency);
        set(8, vendor);
        set(9, azimuth);
        set(10, ssid);
        set(11, auth);
        set(12, polarization);
        set(13, country);
        set(14, norm);
        set(15, area);
        set(16, aggregation);
        set(17, width);
        set(18, antenna);
        set(19, power);
        set(20, master);
        set(21, linkto);
        set(22, hardware);
        set(23, tdma);
        set(24, latitude);
        set(25, longitude);
        set(26, rUpdatetime);
        set(27, rFirmware);
        set(28, rPlatform);
        set(29, rSignal);
        set(30, rCcq);
        set(31, rTxrate);
        set(32, rRxrate);
        set(33, rQuality);
        set(34, rCapacity);
        set(35, rLanspeed);
        set(36, rTxpower);
        set(37, monitoring);
        set(38, traceroute);
        set(39, ping);
        set(40, rFrequency);
        set(41, model);
        set(42, uplinkPort);
        set(43, rstpNumRing);
        set(44, uplinkSfpTx);
        set(45, linktoPort);
        set(46, service);
        set(47, portInfo);
        set(48, zbxGroups);
        set(49, version);
    }
}
